version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    networks:
      - local-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    networks:
      - local-kafka
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092,
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_L://localhost:9092,PLAINTEXT_C://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    healthcheck:
      # Usar kafka-broker-api-versions.sh para verificar la conexión
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server broker:29092 || exit 1"]
      interval: 5s       # Frecuencia de la prueba
      timeout: 10s       # Tiempo máximo para una prueba
      retries: 5         # Número de reintentos antes de considerar 'unhealthy'
      start_period: 30s  # Dar tiempo al servicio para iniciar antes de las comprobaciones

  # schema-registry: # ⬅️ NUEVO SERVICIO
  #   image: confluentinc/cp-schema-registry:7.5.0 # Usamos la misma versión de Confluent para consistencia
  #   container_name: schema-registry
  #   hostname: schema-registry
  #   networks:
  #     - local-kafka
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     broker:
  #       condition: service_healthy
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  #     # 🔑 CLAVE: Conexión al broker usando el listener interno (PLAINTEXT_INTERNAL://broker:29092)
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
  #     # SCHEMA_REGISTRY_DEBUG: 'true' # Descomentar para debug
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - local-kafka
    depends_on: 
      - broker
    ports:
      - "7777:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_PROPERTIES_listener_name=PLAINTEXT_C

  broker-setup:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker-setup
    networks:
      - local-kafka
    volumes:
      - ./create-topics.sh:/usr/bin/create-topics.sh
    # Comando de entrada: ejecutar el script y salir
    entrypoint: [ "/bin/bash", "/usr/bin/create-topics.sh" ]
    depends_on:
      broker:
        condition: service_healthy # Dependencia estricta del healthcheck de Kafka

networks:
  local-kafka:
    driver: bridge