version: '3.8'

services:
  # Servicio para tu aplicación FastAPI
  api:
    container_name: ${API_CONTAINER_NAME} # Nombre del contenedor como variable
    build: .
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      # test: ["CMD-SHELL", "curl --fail http://localhost:8000/docs || exit 1"]
      test: ["CMD-SHELL", "curl --fail http://${API_HEALTHCHECK_HOST}:${API_HEALTHCHECK_PORT}/docs || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  # Servicio para la base de datos PostgreSQL
  db:
    container_name: ${DB_CONTAINER_NAME} # Nombre del contenedor como variable
    image: postgres:15-alpine
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${DATABASE__USERNAME}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
      POSTGRES_DB: ${DATABASE__DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: