"""Add bitacora entity

Revision ID: 904758d4a877
Revises: be24780c0da0
Create Date: 2025-09-18 16:38:10.621484

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "904758d4a877"
down_revision = "be24780c0da0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bitacora",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("entity", sa.String(length=512), nullable=False),
        sa.Column("action", sa.String(length=512), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_account.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bitacora_action"), "bitacora", ["action"], unique=False)
    op.create_index(op.f("ix_bitacora_entity"), "bitacora", ["entity"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bitacora_entity"), table_name="bitacora")
    op.drop_index(op.f("ix_bitacora_action"), table_name="bitacora")
    op.drop_table("bitacora")
    # ### end Alembic commands ###
