version: '3.8'

services:
  # fastapi-app:
  #   container_name: fastapi-app
  #   image: ${FASTAPI_IMAGE}
  #   build:
  #     context: ./path-to-your-fastapi-app
  #     dockerfile: Dockerfile
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=${FASTAPI_OTEL_ENDPOINT}
  #     - OTEL_RESOURCE_ATTRIBUTES=service.name=${FASTAPI_SERVICE_NAME}
  #   ports:
  #     - "${FASTAPI_PORT}:80"
  #   networks:
  #     - observability-network
  #   depends_on:
  #     - otel-collector

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"  # gRPC
      - "4318:4318"  # HTTP
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config", "/etc/otel-collector-config.yaml"]
    networks:
      - observability-network

  jaeger: #Trazas service
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"  # UDP port for Jaeger agent
      - "16686:16686"    # Web UI
      - "14268:14268"    # HTTP port for spans
    networks:
      - observability-network

  prometheus: #Métricas service
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - observability-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - observability-network
    depends_on:
      - prometheus
      - loki

  loki: #Logs service
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      # - loki_data:/loki
    command: -config.file=/etc/loki/config.yaml
    networks:
      - observability-network

networks:
  observability-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
