receivers:
 otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus: # El exportador de Prometheus del colector
    endpoint: "0.0.0.0:9090"
  otlphttp: # <-- ¡Aquí está el exportador que faltaba!
    endpoint: http://loki:3100/api/prom/push

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp] # Enviar trazas a Jaeger usando OTLP
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs: # Para logs
      receivers: [otlp]
      exporters: [otlphttp] # Enviar logs a Loki usando otlphttp
