CREATE_OPERATION = "create"
GET_ALL_OPERATION = "get_all"
GET_ONE_OPERATION = "get_one"
UPDATE_OPERATION = "update"
DELETE_OPERATION = "delete"

ALL_OPERATIONS = [
    GET_ALL_OPERATION,
    GET_ONE_OPERATION,
    CREATE_OPERATION,
    UPDATE_OPERATION,
    DELETE_OPERATION,
]