CREATE_OPERATION = "CREATE"
GET_ALL_OPERATION = "READ_ALL"
GET_ONE_OPERATION = "READ_ONE"
UPDATE_OPERATION = "UPDATE"
DELETE_OPERATION = "DELETE"
GET_BY_FILTERS = "GET_BY_FILTERS"
GET_COUNT_OPERATION = "COUNT"

ALL_OPERATIONS = [
    GET_ALL_OPERATION,
    GET_ONE_OPERATION,
    CREATE_OPERATION,
    UPDATE_OPERATION,
    DELETE_OPERATION,
    GET_COUNT_OPERATION
]

READ_ONLY = [
    GET_ALL_OPERATION,
    GET_ONE_OPERATION,
    GET_BY_FILTERS,
    GET_COUNT_OPERATION
]

READ_WRITE = [
    GET_ALL_OPERATION,
    GET_ONE_OPERATION,
    CREATE_OPERATION,
    UPDATE_OPERATION,
    GET_BY_FILTERS,
    GET_COUNT_OPERATION
]

MUTATION_OPERATIONS = [
    CREATE_OPERATION,
    UPDATE_OPERATION,
    DELETE_OPERATION,
]

# Útil para recursos donde el usuario solo puede acceder a su instancia
OWNER_OPERATIONS = [
    GET_ONE_OPERATION,
    UPDATE_OPERATION,
    DELETE_OPERATION,
    GET_COUNT_OPERATION
]